version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: stahnma/vanagon-builder
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: echo "Attempting a remote vanagon build"
      - run: time make package
      - store_artifacts:
          path: ./pkg
