version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: stahnma/vanagon-builder
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: echo "Hi I'm on Runners!"
      - run: make fluffy
      - store_artifacts:
          path: /work/pkg
