version: 2.1
workflows:
  testing:
    jobs:
      - build-puppet-agent-armhf
jobs:
  build-puppet-agent-armhf:
    machine: true
    resource_class: stahnma/vanagon-builder
    steps:
      - checkout
      - run: echo "Attempting a remote vanagon build"
      - run: time make package
      - store_artifacts:
          path: ./pkg
